version: '3.4'

services:

  traefik:
    container_name: traefik
    image: traefik:1.7.12-alpine
    ports:
      - "80:80"
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock